### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by amazansky** [PlanHubMe/PlanHub#361] opened 2016-02-04 00:35 UTC
This was just an idea... It may be totally weird
So say my name is "Random Person". I am an admin for PlanHub. When my name appeared in stuff like login, feedback, etc., it would say something like "Random Person [Admin]" but with the badge in red or something. Faculty would be "Random Person [Teacher]" or something.

Would this be hard to code? I don't think so...

**Comment by thatoddmailbox** [comment] 2016-02-04 00:56
@RobotXLabs to do this on the username in the top right would be easy, but to do it in feedback would require a database call for each feedback (!) because it would have to look up their status. I think those are the only places where it says usernames or name.

The problem is that the only place we can do this is for your own username, which isn't so helpful...

**Comment by willbarkoff** [comment] 2016-02-04 00:58
@RobotXLabs Way ahead of you:
![screen shot 2016-02-03 at 7 54 16 pm](https://cloud.githubusercontent.com/assets/10969136/12802206/195b6852-cab0-11e5-9730-dd294b6b93b2.png)

**Comment by thatoddmailbox** [comment] 2016-02-04 00:58
@RobotXLabs (@nywillb changed his name to add that)

**Comment by amazansky** [comment] 2016-02-04 00:58
Umm.... Is that part of your name...

**Comment by amazansky** [comment] 2016-02-04 00:58
Yep

**Comment by amazansky** [comment] 2016-02-04 00:59
I was thinking something in a colored box so its official
Like Will [`Admin`] but with color

**Comment by thatoddmailbox** [comment] 2016-02-04 01:01
@RobotXLabs but _hao is halpful_? I can see it being useful for feedback, but that would probably need major_join_hex with knex that I'm not really sure how to do.

**Comment by amazansky** [comment] 2016-02-04 01:02
Idk it was just an idea

**Comment by willbarkoff** [comment] 2016-02-07 03:45
This isn't needed because of 4c7ca6e. Closing.

**Comment by willbarkoff** [comment] 2016-02-08 15:46
Actually re openeing because it's easy

**Comment by amazansky** [comment] 2016-02-08 23:37
Reopening because there's a glitch. Please fix.

**Comment by willbarkoff** [comment] 2016-02-09 01:26
@RobotXLabs #369.

**Closed as completed by willbarkoff** 2016-02-09 01:26 UTC

**Comment by amazansky** [comment] 2016-02-09 01:56
Oh lel
