### ISSUE TITLE
User Menu css issues

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#383] opened 2016-02-20 02:00 UTC
![planhub](https://cloud.githubusercontent.com/assets/10969136/13193740/de875a62-d74b-11e5-9c99-35f8f3e85e00.png)

**Comment by thatoddmailbox** [comment] 2016-02-20 02:01
@nywillb the badge issue is a duplicate of #369

**Closed as completed** 2016-02-20 02:08 UTC
