### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#28] opened 2015-10-26 14:25 UTC
The tabs on the side of the planner do not look great. Could we have a dropdown in the menubar? Also, users like customization. Is it possible to allow users to choose their own plan book title and color scheme?

**Comment by medensqui** [comment] 2015-10-26 14:25
@nywillb @thatoddmailbox I was thinking a preferences tab pls?

**Comment by medensqui** [comment] 2015-10-26 14:25
@nywillb But agree. Also @thatoddmailbox Use more bootstrap

**Comment by thatoddmailbox** [comment] 2015-10-26 15:03
@nywillb @medensqui Could you be specific-ish (separate into multiple issues please?)

I was thinking maybe add icons to the tabs and maybe make them horizontal.

**Comment by willbarkoff** [comment] 2015-10-28 22:19
@thatoddmailbox I was saying we should have a dropdown in the menubar instead of tabs, and have a preferences page to change color scheme and and title.

**Comment by willbarkoff** [comment] 2015-11-03 01:39
Why did it close just because I referenced it?

**Comment by thatoddmailbox** [comment] 2015-11-03 01:40
@nywillb because you wrote `fix #28`. When GitHub sees `close(s) <some issue>` or `fix(es) <some issue>`, it automatically closes it for you.

**Comment by willbarkoff** [comment] 2015-11-03 01:40
@thatoddmailbox Thanks. Also could you help me fix this issue?

**Comment by thatoddmailbox** [comment] 2015-11-03 01:42
@nywillb Sure. Do not merge your latest commit into stable yet. I will test it locally on my computer.

**Comment by willbarkoff** [comment] 2015-11-03 01:43
@thatoddmailbox I wasnt planning to until I finished fixing it. I have to go for now but will be back in about 30 mins.

**Comment by thatoddmailbox** [comment] 2015-11-03 01:44
@nywillb Ok. I will test and upload screenshots here.

**Comment by willbarkoff** [comment] 2015-11-03 01:44
@thatoddmailbox Thanks!

**Comment by thatoddmailbox** [comment] 2015-11-03 01:54
@nywillb I edited the code so the buttons work. It looks nice!

![screen shot 2015-11-02 at 8 53 24 pm](https://cloud.githubusercontent.com/assets/1904587/10899553/d22d66f6-81a3-11e5-9546-13a559e81164.png)
![screen shot 2015-11-02 at 8 53 12 pm](https://cloud.githubusercontent.com/assets/1904587/10899552/d21df536-81a3-11e5-90a3-f400d09dbdae.png)

**Comment by willbarkoff** [comment] 2015-11-03 02:21
@thatoddmailbox Thank you so much!

**Comment by thatoddmailbox** [comment] 2015-11-03 02:24
@nywillb Do you really want to remove the tabs? I think that if you do remove them, they should be replaced with something as noticeable. Otherwise, new users will sign in, see the date, and be unsure of where to go after that. (the dropdown is not that noticeable...)

**Comment by willbarkoff** [comment] 2015-11-03 02:28
@thatoddmailbox Good Point. What if we got rid of the tabs and added a tour. See #11 and #178. If you like the tabs it is okay.

**Comment by willbarkoff** [comment] 2015-11-03 02:29
@thatoddmailbox Is it possible to get that beta channel up and running quickly? It would really be helpful.

**Comment by thatoddmailbox** [comment] 2015-11-03 02:30
@nywillb That could work, and I think a tour is a smart idea, if we remove the tabs or not. However, we have to make sure the tour doesn't require you to enable everything. For example, if you do not want to use My Day, you should be allowed to not enable it/maybe even hide it from the menus.

Also, I still think the dropdown is somewhat hidden. I don't really love the tabs, but I don't have any better ideas.

**Comment by thatoddmailbox** [comment] 2015-11-03 02:30
@nywillb Ok, I will work on setting up the beta site. It will have a separate database in case we screw something up, and probably will crash a lot.

**Comment by thatoddmailbox** [comment] 2015-11-03 02:32
@nywillb Also, would it be helpful if I provided instructions on how to set up a local environment? It might be possible on student laptops without admin account (and maybe even without bothering new lab).

**Comment by willbarkoff** [comment] 2015-11-03 02:32
@thatoddmailbox It is not possible on student laptops without an admin account (I tried)

**Comment by thatoddmailbox** [comment] 2015-11-03 02:35
@nywillb Are you sure? If I remember, node.js and npm are already installed on all student laptops. (go to terminal, try `node --version`) I could give you a small amount of database space on my server for the storage. (not just for @nywillb but for whoever needs it). (but don't use it for actual production stuff because I might clear it/break it/something)

**Comment by willbarkoff** [comment] 2015-11-03 02:36
@thatoddmailbox It does work (thats weird I tried it before and it didnt)

**Comment by willbarkoff** [comment] 2015-11-03 02:43
@thatoddmailbox Nevermind it doesnt.
![screen shot 2015-11-02 at 9 41 04 pm](https://cloud.githubusercontent.com/assets/10969136/10900175/bb7dd812-81aa-11e5-9c44-efcfd9201012.png)

**Comment by thatoddmailbox** [comment] 2015-11-03 02:52
@nywillb umm. The command is `node www.js`. There is no runme.js file...

**Comment by willweinstein** [comment] 2015-11-03 02:55
@thatoddmailbox can you just make a second website/github combo but that one auto updates from the github so we dont have to wait for you to update stuffs when we need

**Comment by willbarkoff** [comment] 2015-11-03 02:56
@thatoddmailbox Sorry, I'm tired.

**Comment by thatoddmailbox** [comment] 2015-11-03 02:57
@willweinstein that is what @nywillb means by beta site

@nywillb It's ok. Did it work?

**Comment by willbarkoff** [comment] 2015-11-03 02:58
@thatoddmailbox No. I got a bunch of shiny red text.
![screen shot 2015-11-02 at 9 57 51 pm](https://cloud.githubusercontent.com/assets/10969136/10900368/d4409798-81ac-11e5-9e52-945f5f5813f9.png)

**Comment by willweinstein** [comment] 2015-11-03 02:59
@nywillb shiny red text means ur doing everything right and are on the path to becoming **number 1 hexer of da univrs**

**Comment by thatoddmailbox** [comment] 2015-11-03 03:00
@nywillb That is how it complains it couldn't connect to a database. If you go to http://localhost:3000 in your browser, it will work until you try and log in. Do you want me to set up some small database space on my server? or you can try to convince new lab to install mysql on your computer. or you could set it up on another computer and connect to that, but it wouldn't work at school.

**Comment by willbarkoff** [comment] 2015-11-03 03:00
@willweinstein Oh. But it still says "This webpage is unavailable"

**Comment by willbarkoff** [comment] 2015-11-03 03:01
@thatoddmailbox But it doesnt even let me get that far. It just doesnt load.

**Comment by thatoddmailbox** [comment] 2015-11-03 03:02
@nywillb where? in Chrome? Maybe it needs a database before it can load, and I was wrong about it working without db. Does more shiny text come when you try and load the page?

**Comment by willbarkoff** [comment] 2015-11-03 03:02
@thatoddmailbox Nope. It just doesnt load.

**Comment by willbarkoff** [comment] 2015-11-03 03:03
@thatoddmailbox All the problems would be solved if you setup a staging server.

**Comment by willweinstein** [comment] 2015-11-03 03:03
@nywillb just get more shiny text untle teh mujr hx upp oopeens ten yoo weel bee num un hxr

**Comment by thatoddmailbox** [comment] 2015-11-03 03:03
@nywillb I know, I am trying to set one up now. It probably is a database connection issue.

**Comment by thatoddmailbox** [comment] 2015-11-03 03:04
@willweinstein 

> just get more shiny text untle teh mujr hx upp oopeens ten yoo weel bee num un hxr

....

pls translate to teh englishes

**Comment by willweinstein** [comment] 2015-11-03 03:04
@thatoddmailbox 

> just get more shiny text until the major hex app opens then you will be the number one hexer

**Comment by willbarkoff** [comment] 2015-11-03 03:05
@willweinstein  a ii geing teh riht

**Comment by willbarkoff** [comment] 2015-11-03 03:07
@willweinstein 
These links expire in twelve hours. Click on them soon. 
http://shoutkey.com/kohlrabi
http://shoutkey.com/got

**Comment by thatoddmailbox** [comment] 2015-11-03 03:11
@nywillb @willweinstein 
This is an actual program in the amazing Hex programming language that @willweinstein and I created. It compiles fine and runs.

```
hex_prg_setap start
    prgum_nfo->authr = "meh";;;;;;;;;;
    prgum_nfo->dat = "nao";;;;;;;;;;;;;;
    prgum_nfo->tumpuruture = "idk culd";;;;;;;;;;;;;;

    prgum_nfo->yuze_strikt = tru;;;;;;;;;;;;;;;;;;;;
fin

tni mayn(hex_prgum) start
    spat_ut("velcum tu TEST PRUGRUM !!!!1111111eleventyone!11");;;;;;;;;;;
    sput_oot(nu_lyne);;;;;;;;;;;;;

    sput_oot("nu everune");;;;;;;;;;;
    sput_oot(nu_lyne);;;;;;;;;;;;;

    sput_oot("chuncheeelu nu allooooweeed");;;;;;;;;;
    sput_oot(nu_lyne);;;;;;;;;;;;;

    sput_oot("wat iz name? ");;;;;;;;;;;
    srting name = receve_Input();;;;;;;;;;;;

    name = small_Srting(name);;;;;;;;;;;;;;;

    sai_Tuktz(name, "Good News");;;;;;;;;;;;;;

    chek (name iz_equal_to "alex" our name iz_equal_to "will") start
        sput_oot("welcome ");;;;;;;;;;;
        sput_oot(name);;;;;;;;;;
        sput_oot(nu_lyne);;;;;;;;;;;
    fin otharwize chek (name iz_equal_to "ryan") start
        sput_oot("NUUUUU RYAN");;;;;;;;;;;;
        sput_oot(nu_lyne);;;;;;;;;;;;;
    fin otharwize chek (name iz_equal_to "sekret sung mod") start
        sai_Tuktz("a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y z", "Good News");
        sput_oot("sekret sung mod actif!1!111!!1111111eleventyone!1111!!!!!");;;;;;;;;;;;
        sput_oot(nu_lyne);;;;;;;;;;;;;
    fin otharwize start
        sput_oot("hex DEFENZE ACTIF LOL NO HEX");;;;;;;;;;;
        sput_oot(nu_lyne);;;;;;;;;;;;;
    fin

    retyrn 0;;;;;;;;;;;;;;;;;;;;;
fin
```

**Comment by willbarkoff** [comment] 2015-11-03 03:12
@thatoddmailbox and why?

**Comment by thatoddmailbox** [comment] 2015-11-03 03:13
@nywillb why not? 

There are also plans to maybe add a feature to let you write websites in Hex. :smiling_imp:

**Comment by willbarkoff** [comment] 2015-11-06 23:56
@thatoddmailbox @willweinstein @medensqui We should use modals instead of javascript alerts. I personally hate javascript alerts.

**Comment by thatoddmailbox** [comment] 2015-11-07 00:00
@nywillb 

> We should use modals instead of javascript alerts.

+infinite

I don't think many `alert()`s are used, except in HW view if you have no HW (which should be changed) and maybe if there is an error syncing in the planner.

**Comment by willbarkoff** [comment] 2015-11-07 00:01
@thatoddmailbox you are right. _(But what is the +infinate?)_

**Comment by thatoddmailbox** [comment] 2015-11-07 00:03
@nywillb a :+1: (+1) was not enough to express my agreement.

**Comment by amazansky** [comment] 2015-12-13 11:23
WAIT GUYS WHAT ARE WE TRYING TO DO? MAKE A LOCAL WEBPAGE?
BECAUSE IF SO I KNOW A COMMAND
`cd *directory*`
`python -m SimpleHTTPServer *port*`

**Comment by willbarkoff** [comment] 2015-12-13 21:02
@RobotXLabs What are you talking about? (also with ruby and shotgun `shotgun -o 0.0.0.0`)
@thatoddmailbox I installed [SweetAlert](http://t4t5.github.io/sweetalert/) for more shiny alerts.

**Comment by willbarkoff** [comment] 2015-12-13 21:03
Shouldnt close until implemented

**Comment by willbarkoff** [comment] 2015-12-13 21:09
@thatoddmailbox I can't figure out how to change the rename dialog to sweetalert. The sweetalert documentation is [here](http://t4t5.github.io/sweetalert/), but I dont want to mess up any js stuff.

**Comment by willbarkoff** [comment] 2015-12-15 02:41
@thatoddmailbox please help

**Comment by thatoddmailbox** [comment] 2015-12-15 02:51
@nywillb I DID IT

**Comment by willbarkoff** [comment] 2015-12-15 03:23
@thatoddmailbox Yay

**Comment by willbarkoff** [comment] 2015-12-15 03:27
@thatoddmailbox Delete dialogue needs to be done still. I will do it.

**Comment by thatoddmailbox** [comment] 2015-12-17 21:44
Closing because the issue is somewhat open-ended and I think we've finished what has been mentioned here.

__MAKE A NEW ISSUE WITH SPECIFICS IF SOMETHING ISN'T FIXED__

**Closed as completed by thatoddmailbox** 2015-12-17 21:44 UTC
