### ISSUE TITLE
Blank Lines Bug (duplicate)

### ISSUE THREAD

**Issue by willweinstein** [PlanHubMe/PlanHub#160] opened 2015-10-31 03:30 UTC
When you delete text from a box, it generates an enter in that box until you put other text in or studer deletes it (yes unless those happen, it is immortal)

**Comment by thatoddmailbox** [comment] 2015-11-03 13:15
@willweinstein This has probably been partially fixed by #170. Fixing #173 should also close this.

**Comment by thatoddmailbox** [comment] 2015-11-03 17:29
@willweinstein Actually, I think this is a duplicate of #173. Closing...

**Closed as completed by thatoddmailbox** 2015-11-03 17:29 UTC
Labels: bug, duplicate, very high priority
