### ISSUE TITLE
Random question

### ISSUE THREAD

**Issue by prashcr** [PlanHubMe/PlanHub#278] opened 2015-12-27 16:35 UTC
I apologize in advance for bringing this here, I couldn't find any other point of contact.
The puzzle was fun. I reached the google forms link. But after that, it made no sense to me.

Opening the link normally takes me to a Google Forms page that says I'm not authorized.
Opening the link in Incognito mode takes me to a Dalton School login page, which I found pretty strange.

Is this expected behavior?

**Comment by willbarkoff** [comment] 2015-12-27 17:06
Hi @prashcr,
PlanHub was intended to be only open to members of The Dalton School, so we made the "work with us" form require a Dalton login page. We have fixed that issue, and you can go to the same link and fill out the form as normal. It now requires a Google Login instead of a Dalton School login. After you complete the form, we will be in touch with you via email. Thank you for your interest in PlanHub!
Hope this helps!

**Closed as completed** 2015-12-27 17:07 UTC
